apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config-template
  labels:
    app: redis
data:
  redis.conf: |
    maxmemory 400mb
    maxmemory-policy allkeys-lru
    maxclients 20000
    timeout 300
    appendonly no
    dbfilename dump.rdb
    dir /data
